services:
  nginx:
    image: nginx:alpine
    ports:
    - 8000:8000
    volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
    - whisperx
    - yolo
  whisperx:
    build:
      context: .
      args:
        MODEL_NAME: whisperx
    environment:
    - MODEL_NAME=whisperx
    - TORCH_HOME=/app/.cache/torch
    - HF_HOME=/app/.cache/huggingface
    - YOLO_CONFIG_DIR=/app/.cache/yolo
    - HF_TOKEN=${HF_TOKEN}
    - WHISPERX_SIZE=base
    - COMPUTE_TYPE=int8
    volumes:
    - ./.models:/app/.cache
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities:
            - gpu
  yolo:
    build:
      context: .
      args:
        MODEL_NAME: yolo
    environment:
    - MODEL_NAME=yolo
    - TORCH_HOME=/app/.cache/torch
    - HF_HOME=/app/.cache/huggingface
    - YOLO_CONFIG_DIR=/app/.cache/yolo
    volumes:
    - ./.models:/app/.cache
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities:
            - gpu
