apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-service-pvc
  namespace: model-service
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: ephemeral
  