{{- if and .Values.appSecret.create (gt (len .Values.appSecret.stringData) 0) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "model-service-stage3.appSecretName" . }}
  namespace: {{ include "model-service-stage3.namespace" . }}
  labels:
    {{- include "model-service-stage3.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- toYaml .Values.appSecret.stringData | nindent 2 }}
{{- end }}
