{{- if .Values.cache.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "model-service-stage3.cachePvcName" . }}
  namespace: {{ include "model-service-stage3.namespace" . }}
  labels:
    {{- include "model-service-stage3.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.cache.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.cache.size }}
  {{- with .Values.cache.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
{{- end }}
