{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "model-service-stage3.serviceAccountName" . }}
  namespace: {{ include "model-service-stage3.namespace" . }}
  labels:
    {{- include "model-service-stage3.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- if or .Values.serviceAccount.imagePullSecrets .Values.imagePullSecret.create }}
imagePullSecrets:
  {{- range .Values.serviceAccount.imagePullSecrets }}
  - name: {{ . }}
  {{- end }}
  {{- if .Values.imagePullSecret.create }}
  - name: {{ include "model-service-stage3.imagePullSecretName" $ }}
  {{- end }}
{{- end }}
{{- end }}
