apiVersion: v1
kind: Service
metadata:
  name: {{ include "model-service-stage3.fullname" . }}
  namespace: {{ include "model-service-stage3.namespace" . }}
  labels:
    {{- include "model-service-stage3.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "model-service-stage3.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
